//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lemoncellar.modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONSUMIBLE_I
    {
        public int ID_CONSUMIBLE_I { get; set; }
        public Nullable<int> ID_CONSUMIBLE { get; set; }
        public Nullable<int> VALOR { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public Nullable<int> CANTIDAD_IC { get; set; }
    
        public virtual CONSUMIBLE CONSUMIBLE { get; set; }
    }
}
