//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lemoncellar.modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONSUMIBLE
    {
        public CONSUMIBLE()
        {
            this.CONSUMIBLE_G = new HashSet<CONSUMIBLE_G>();
            this.CONSUMIBLE_I = new HashSet<CONSUMIBLE_I>();
        }
    
        public int ID_CONSUMIBLE { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
        public string DETALLE { get; set; }
    
        public virtual ICollection<CONSUMIBLE_G> CONSUMIBLE_G { get; set; }
        public virtual ICollection<CONSUMIBLE_I> CONSUMIBLE_I { get; set; }
    }
}
