//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lemoncellar.modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class HERRAMIENTA
    {
        public int ID_HERRAMIENTA { get; set; }
        public string NOMBRE { get; set; }
        public string DETALLE { get; set; }
        public Nullable<int> VALOR { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string ESTADO { get; set; }
    }
}
