//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lemoncellar.modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATERIAL
    {
        public MATERIAL()
        {
            this.MATERIAL_I = new HashSet<MATERIAL_I>();
            this.MATERIAL_S = new HashSet<MATERIAL_S>();
        }
    
        public int ID_MATERIAL { get; set; }
        public string NOMBRE { get; set; }
        public string TIPO { get; set; }
        public string MEDIDA { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
    
        public virtual ICollection<MATERIAL_I> MATERIAL_I { get; set; }
        public virtual ICollection<MATERIAL_S> MATERIAL_S { get; set; }
    }
}
