//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lemoncellar.modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class lemoncellarEntities : DbContext
    {
        public lemoncellarEntities()
            : base("name=lemoncellarEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CONSUMIBLE> CONSUMIBLE { get; set; }
        public DbSet<CONSUMIBLE_G> CONSUMIBLE_G { get; set; }
        public DbSet<CONSUMIBLE_I> CONSUMIBLE_I { get; set; }
        public DbSet<HERRAMIENTA> HERRAMIENTA { get; set; }
        public DbSet<MATERIAL> MATERIAL { get; set; }
        public DbSet<MATERIAL_I> MATERIAL_I { get; set; }
        public DbSet<MATERIAL_S> MATERIAL_S { get; set; }
        public DbSet<USUARIO> USUARIO { get; set; }
    }
}
